### ISSUE TITLE
will it support img2img case？

### ISSUE THREAD

**Issue by t00350320** [MoayedHajiAli/ElasticDiffusion-official#4]
hi, MoayedHajiAli
    I have experienced your  excellent demo on https://replicate.com/moayedhajiali/elasticdiffusion, i wonder will you support img2img usage like face swap case?
thank you!!!

**Comment by MoayedHajiAli** [comment]
Hello @t00350320, 
Our method is compatible with ControlNet which allows for Img2Img applications. We will soon update our code to include ControlNet.

**Comment by heorhiikalaichev** [comment]
Looking forward to try to use an Img2Img version!

**Comment by MoayedHajiAli** [comment]
Apologies for the delay in adding Img2Img pipeline. 
As promised, I included the implementation and a demo of integrating ElasticDiffusion with ControlNet. However, I noticed a _huge_ decrease in the quality of the generated images. I am still investigating the reason behind this degradation.
