### ISSUE TITLE
Get bad results when use controlnet

### ISSUE THREAD

**Issue by YoucanBaby** [MoayedHajiAli/ElasticDiffusion-official#6]
Dear developer,

Thanks for your great job.

I get bad results when use txt2img with controlnet.
Why does controlnet lead to serious image quality degradation?

Best wishes.

**Comment by MoayedHajiAli** [comment]
Hello @YoucanBaby, 
Apologies for the late reply. As highlighted in the README, the visual quality noticeably degraded when integrating ControlNet with ElasticDiffusion. Although the exact cause is unclear, I suspect it relates to differences in how we adapt ElasticDiffusion to a pre-trained ControlNet compared to its original training scheme. Particularly, to adapt the pre-trained ControlNet, we partition the conditioning map similarly to how we partition the intermediate latent space when computing the unconditional score, which could explain the diminished results. Retraining the ControlNet might help improving the visual quality.
